name: Fabric Deployment Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'Customer-A/**'
      - 'Customer-B/**'

jobs:
  detect_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Maagcha commit compare karnyasaathi garjeche aahe

      # 1. Kontya folder madhe badal jhalay te check kara
      - name: Detect Changed Customer
        id: filter
        run: |
          echo "Checking for changes..."
          if git diff --name-only HEAD^ HEAD | grep -q '^Customer-A/'; then
            echo "customer=Customer-A" >> $GITHUB_OUTPUT
            echo "workspace_id=09426049-3a4b-4063-b35b-43928a03b21a" >> $GITHUB_OUTPUT
            echo "pipeline_id=2c6e8fa5-112c-4e07-8254-4f5ab8ed2f75" >> $GITHUB_OUTPUT
          elif git diff --name-only HEAD^ HEAD | grep -q '^Customer-B/'; then
            echo "customer=Customer-B" >> $GITHUB_OUTPUT
            echo "workspace_id=TUMCHA_CUSTOMER_B_WORKSPACE_ID" >> $GITHUB_OUTPUT
            echo "pipeline_id=TUMCHA_CUSTOMER_B_PIPELINE_ID" >> $GITHUB_OUTPUT
          else
            echo "No specific customer folder changed."
          fi

      # 2. Fabric Access Token ghyaycha
      - name: Get Fabric Token
        if: steps.filter.outputs.customer != ''
        id: get_token
        run: |
          TOKEN=$(curl -s -X POST https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.CLIENT_ID }}" \
            -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
            -d "resource=https://analysis.windows.net/powerbi/api" | jq -r .access_token)
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      # 3. DEV Workspace Sync kara (Git credentials nitt asle pahijet Fabric madhe)
      - name: Sync Fabric DEV Workspace
        if: steps.filter.outputs.customer != ''
        run: |
          echo "Syncing Workspace: ${{ steps.filter.outputs.customer }}"
          curl -X POST https://api.fabric.microsoft.com/v1/workspaces/${{ steps.filter.outputs.workspace_id }}/git/updateFromGit \
          -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d "{\"remoteCommitHash\": \"${{ github.sha }}\"}"

      # 4. Fabric Deployment Pipeline Trigger kara (Dev -> QA)
      - name: Trigger Fabric Deployment Pipeline
        if: steps.filter.outputs.customer != ''
        run: |
          echo "Triggering Pipeline for: ${{ steps.filter.outputs.customer }}"
          curl -X POST https://api.powerbi.com/v1.0/myorg/pipelines/${{ steps.filter.outputs.pipeline_id }}/deploy \
          -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d "{\"sourceStageOrder\": 0, \"isSourceJustNowUpdated\": true, \"note\": \"Jenkins-GitHub Auto-Deploy for ${{ steps.filter.outputs.customer }}\"}"
